# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on:
      labels: guwdbebuild04

    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Maven
      run: /mnt/tsi/root/external/maven/3.9.6/bin/mvn clean install
    
    - name: Package
      run: cd pkg; /mnt/tsi/root/external/maven/3.9.6/bin/mvn dependency:copy-dependencies -DoutputDirectory=libs;

    - name: Test Run
      run: java -cp libs:libs/app-1.1-SNAPSHOT.jar:libs/module1-1.0.jar:libs/module2-1.1-SNAPSHOT.jar:libs/log4j-api-2.11.2.jar:libs/log4j-core-2.11.2.jar com.tibco.mvndemo.App
